// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Animal interface {
	IsAnimal()
	GetID() string
}

type Dog struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (Dog) IsAnimal()          {}
func (this Dog) GetID() string { return this.ID }
